import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'fa' | 'ru' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRTL: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    settings: 'Settings',
    appearance: 'Appearance',
    theme: 'Theme',
    lightMode: 'Light mode',
    darkMode: 'Dark mode',
    language: 'Language',
    autoUpdate: 'Auto Update',
    autoUpdateDesc: 'Automatically update the application',
    english: 'English',
    persian: 'Persian',
    russian: 'Russian',
    chinese: 'Chinese',
    candyConnect: 'CandyConnect',
    cores: 'Cores',
    v2rayCore: 'V2ray Core',
    wireGuard: 'WireGuard',
    singBox: 'Sing-Box',
    xray: 'Xray',
    amnezia: 'Amnezia',
    nativeWireGuard: 'Native WireGuard',
    profiles: 'Profiles',
    proxy: 'Proxy',
    about: 'About',
    version: 'Version',
    github: 'GitHub',
    description: 'A modern VPN client with multiple core support',
    logs: 'Logs',
    addProfile: 'Add Profile',
    editProfile: 'Edit Profile',
    deleteProfile: 'Delete Profile',
    deleteProfiles: 'Delete Profiles',
    selectProfile: 'Select Profile',
    profileName: 'Profile Name',
    profileUrl: 'Profile URL',
    fromClipboard: 'From Clipboard',
    fromQRCode: 'From QR Code',
    manually: 'Manually',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    select: 'Select',
    selected: 'Selected',
    noProfiles: 'No profiles available',
    confirmDelete: 'Are you sure you want to delete this profile?',
    confirmDeleteMultiple: 'Are you sure you want to delete selected profiles?',
    connectionMode: 'Connection Mode',
    selectConnectionMode: 'Select your preferred connection mode',
    proxyType: 'Proxy Type',
    selectProxyType: 'Choose the proxy protocol',
    connectionSettings: 'Connection Settings',
    configureProxyConnection: 'Configure proxy server connection',
    ipAddress: 'IP Address',
    port: 'Port',
    authentication: 'Authentication',
    enableAuthIfRequired: 'Enable if your proxy requires authentication',
    username: 'Username',
    password: 'Password',
    enterUsername: 'Enter username',
    enterPassword: 'Enter password',
    tunModeActive: 'TUN Mode Active',
    tunModeInfo: 'TUN mode creates a virtual network interface for system-wide traffic routing.',
    tunModeDesc: 'System-wide routing',
    proxyModeDesc: 'Application-level proxy',
    socksProxyDesc: 'SOCKS5 protocol',
    httpProxyDesc: 'HTTP/HTTPS protocol',
    currentSettings: 'Current Settings',
    mode: 'Mode',
    type: 'Type',
    address: 'Address',
    enabled: 'Enabled',
    disabled: 'Disabled',
    // Login
    vpnClient: 'VPN Client',
    serverAddress: 'Server Address',
    login: 'Login',
    logout: 'Logout',
    rememberMe: 'Remember me',
    loginFailed: 'Login failed',
    connectionError: 'Could not connect to server',
    connecting: 'Connecting',
    fillAllFields: 'Please fill in all fields',
    // Protocols
    selectProtocol: 'Select Protocol',
    protocolStatus: 'Status',
    activeConnections: 'Active Connections',
    connected: 'Connected',
    disconnected: 'Disconnected',
    offline: 'Offline',
    connect: 'Connect',
    disconnect: 'Disconnect',
    refresh: 'Refresh',
    // Account
    accountInfo: 'Account Info',
    trafficUsage: 'Traffic Usage',
    trafficLimit: 'Traffic Limit',
    timeRemaining: 'Time Remaining',
    remaining: 'remaining',
    expiresAt: 'Expires',
    createdAt: 'Created',
    connectionHistory: 'Connection History',
    enabledProtocols: 'Enabled Protocols',
    active: 'Active',
    onHold: 'On Hold',
    // Navigation
    home: 'Home',
    account: 'Account',
    protocols: 'Protocols',
    // Settings extras
    autoReconnect: 'Auto Reconnect',
    autoReconnectDesc: 'Automatically reconnect if connection drops',
    killSwitch: 'Kill Switch',
    killSwitchDesc: 'Block internet if VPN disconnects',
    dnsLeakProtection: 'DNS Leak Protection',
    dnsLeakProtectionDesc: 'Prevent DNS queries outside VPN tunnel',
    splitTunneling: 'Split Tunneling',
    splitTunnelingDesc: 'Route only selected apps through VPN',
    security: 'Security',
    general: 'General',
    server: 'Server',
    confirmLogout: 'Are you sure you want to logout?',
    autoPilot: 'Auto Pilot',
    autoPilotDesc: 'Automatically switch to the best connection',
    findBestConnection: '🔍 Find Best Connection',
  },
  fa: {
    settings: 'تنظیمات',
    appearance: 'ظاهر',
    theme: 'تم',
    lightMode: 'حالت روشن',
    darkMode: 'حالت تاریک',
    language: 'زبان',
    autoUpdate: 'به‌روزرسانی خودکار',
    autoUpdateDesc: 'به‌روزرسانی خودکار برنامه',
    english: 'انگلیسی',
    persian: 'فارسی',
    russian: 'روسی',
    chinese: 'چینی',
    candyConnect: 'کندی‌کانکت',
    cores: 'هسته‌ها',
    v2rayCore: 'هسته V2ray',
    wireGuard: 'وایرگارد',
    singBox: 'سینگ‌باکس',
    xray: 'ایکس‌ری',
    amnezia: 'آمنزیا',
    nativeWireGuard: 'وایرگارد بومی',
    profiles: 'پروفایل‌ها',
    proxy: 'پروکسی',
    about: 'درباره',
    version: 'نسخه',
    github: 'گیت‌هاب',
    description: 'کلاینت مدرن VPN با پشتیبانی از هسته‌های متعدد',
    logs: 'لاگ‌ها',
    addProfile: 'افزودن پروفایل',
    editProfile: 'ویرایش پروفایل',
    deleteProfile: 'حذف پروفایل',
    deleteProfiles: 'حذف پروفایل‌ها',
    selectProfile: 'انتخاب پروفایل',
    profileName: 'نام پروفایل',
    profileUrl: 'آدرس پروفایل',
    fromClipboard: 'از کلیپ‌بورد',
    fromQRCode: 'از کد QR',
    manually: 'دستی',
    cancel: 'لغو',
    save: 'ذخیره',
    delete: 'حذف',
    edit: 'ویرایش',
    select: 'انتخاب',
    selected: 'انتخاب شده',
    noProfiles: 'هیچ پروفایلی موجود نیست',
    confirmDelete: 'آیا مطمئن هستید که می‌خواهید این پروفایل را حذف کنید؟',
    confirmDeleteMultiple: 'آیا مطمئن هستید که می‌خواهید پروفایل‌های انتخاب شده را حذف کنید؟',
    connectionMode: 'حالت اتصال',
    selectConnectionMode: 'حالت اتصال مورد نظر خود را انتخاب کنید',
    proxyType: 'نوع پروکسی',
    selectProxyType: 'پروتکل پروکسی را انتخاب کنید',
    connectionSettings: 'تنظیمات اتصال',
    configureProxyConnection: 'اتصال سرور پروکسی را پیکربندی کنید',
    ipAddress: 'آدرس IP',
    port: 'پورت',
    authentication: 'احراز هویت',
    enableAuthIfRequired: 'در صورت نیاز پروکسی به احراز هویت فعال کنید',
    username: 'نام کاربری',
    password: 'رمز عبور',
    enterUsername: 'نام کاربری را وارد کنید',
    enterPassword: 'رمز عبور را وارد کنید',
    tunModeActive: 'حالت TUN فعال',
    tunModeInfo: 'حالت TUN یک رابط شبکه مجازی برای مسیریابی ترافیک سیستم ایجاد می‌کند.',
    tunModeDesc: 'مسیریابی سیستمی',
    proxyModeDesc: 'پروکسی سطح برنامه',
    socksProxyDesc: 'پروتکل SOCKS5',
    httpProxyDesc: 'پروتکل HTTP/HTTPS',
    currentSettings: 'تنظیمات فعلی',
    mode: 'حالت',
    type: 'نوع',
    address: 'آدرس',
    enabled: 'فعال',
    disabled: 'غیرفعال',
    vpnClient: 'کلاینت VPN',
    serverAddress: 'آدرس سرور',
    login: 'ورود',
    logout: 'خروج',
    rememberMe: 'مرا به خاطر بسپار',
    loginFailed: 'ورود ناموفق',
    connectionError: 'عدم اتصال به سرور',
    connecting: 'در حال اتصال',
    fillAllFields: 'لطفا تمام فیلدها را پر کنید',
    selectProtocol: 'انتخاب پروتکل',
    protocolStatus: 'وضعیت',
    activeConnections: 'اتصالات فعال',
    connected: 'متصل',
    disconnected: 'قطع شده',
    offline: 'آفلاین',
    connect: 'اتصال',
    disconnect: 'قطع اتصال',
    refresh: 'بروزرسانی',
    accountInfo: 'اطلاعات حساب',
    trafficUsage: 'مصرف ترافیک',
    trafficLimit: 'محدودیت ترافیک',
    timeRemaining: 'زمان باقیمانده',
    remaining: 'باقیمانده',
    expiresAt: 'انقضا',
    createdAt: 'ایجاد شده',
    connectionHistory: 'تاریخچه اتصال',
    enabledProtocols: 'پروتکل‌های فعال',
    active: 'فعال',
    onHold: 'متوقف',
    home: 'خانه',
    account: 'حساب',
    protocols: 'پروتکل‌ها',
    autoReconnect: 'اتصال مجدد خودکار',
    autoReconnectDesc: 'اتصال مجدد خودکار در صورت قطع',
    killSwitch: 'کیل سوئیچ',
    killSwitchDesc: 'قطع اینترنت در صورت قطع VPN',
    dnsLeakProtection: 'محافظت از نشت DNS',
    dnsLeakProtectionDesc: 'جلوگیری از درخواست‌های DNS خارج از تونل',
    splitTunneling: 'تونل‌زنی تقسیمی',
    splitTunnelingDesc: 'هدایت فقط برنامه‌های منتخب از طریق VPN',
    security: 'امنیت',
    general: 'عمومی',
    server: 'سرور',
    confirmLogout: 'آیا مطمئنید که می‌خواهید خارج شوید؟',
    autoPilot: 'خلبان خودکار',
    autoPilotDesc: 'تغییر خودکار به بهترین اتصال',
    findBestConnection: '🔍 یافتن بهترین اتصال',
  },
  ru: {
    settings: 'Настройки',
    appearance: 'Внешний вид',
    theme: 'Тема',
    lightMode: 'Светлая тема',
    darkMode: 'Тёмная тема',
    language: 'Язык',
    autoUpdate: 'Автообновление',
    autoUpdateDesc: 'Автоматически обновлять приложение',
    english: 'Английский',
    persian: 'Персидский',
    russian: 'Русский',
    chinese: 'Китайский',
    candyConnect: 'CandyConnect',
    cores: 'Ядра',
    v2rayCore: 'Ядро V2ray',
    wireGuard: 'WireGuard',
    singBox: 'Sing-Box',
    xray: 'Xray',
    amnezia: 'Amnezia',
    nativeWireGuard: 'Нативный WireGuard',
    profiles: 'Профили',
    proxy: 'Прокси',
    about: 'О программе',
    version: 'Версия',
    github: 'GitHub',
    description: 'Современный VPN клиент с поддержкой множества ядер',
    logs: 'Логи',
    addProfile: 'Добавить профиль',
    editProfile: 'Редактировать профиль',
    deleteProfile: 'Удалить профиль',
    deleteProfiles: 'Удалить профили',
    selectProfile: 'Выбрать профиль',
    profileName: 'Имя профиля',
    profileUrl: 'URL профиля',
    fromClipboard: 'Из буфера обмена',
    fromQRCode: 'Из QR-кода',
    manually: 'Вручную',
    cancel: 'Отмена',
    save: 'Сохранить',
    delete: 'Удалить',
    edit: 'Редактировать',
    select: 'Выбрать',
    selected: 'Выбрано',
    noProfiles: 'Нет доступных профилей',
    confirmDelete: 'Вы уверены, что хотите удалить этот профиль?',
    confirmDeleteMultiple: 'Вы уверены, что хотите удалить выбранные профили?',
    connectionMode: 'Режим подключения',
    selectConnectionMode: 'Выберите предпочтительный режим подключения',
    proxyType: 'Тип прокси',
    selectProxyType: 'Выберите протокол прокси',
    connectionSettings: 'Настройки подключения',
    configureProxyConnection: 'Настройте подключение к прокси-серверу',
    ipAddress: 'IP-адрес',
    port: 'Порт',
    authentication: 'Аутентификация',
    enableAuthIfRequired: 'Включите, если ваш прокси требует аутентификации',
    username: 'Имя пользователя',
    password: 'Пароль',
    enterUsername: 'Введите имя пользователя',
    enterPassword: 'Введите пароль',
    tunModeActive: 'Режим TUN активен',
    tunModeInfo: 'Режим TUN создает виртуальный сетевой интерфейс для системной маршрутизации трафика.',
    tunModeDesc: 'Системная маршрутизация',
    proxyModeDesc: 'Прокси уровня приложения',
    socksProxyDesc: 'Протокол SOCKS5',
    httpProxyDesc: 'Протокол HTTP/HTTPS',
    currentSettings: 'Текущие настройки',
    mode: 'Режим',
    type: 'Тип',
    address: 'Адрес',
    enabled: 'Включено',
    disabled: 'Отключено',
    vpnClient: 'VPN Клиент',
    serverAddress: 'Адрес сервера',
    login: 'Войти',
    logout: 'Выйти',
    rememberMe: 'Запомнить',
    loginFailed: 'Ошибка входа',
    connectionError: 'Не удалось подключиться к серверу',
    connecting: 'Подключение',
    fillAllFields: 'Заполните все поля',
    selectProtocol: 'Выбрать протокол',
    protocolStatus: 'Статус',
    activeConnections: 'Активные соединения',
    connected: 'Подключено',
    disconnected: 'Отключено',
    offline: 'Офлайн',
    connect: 'Подключить',
    disconnect: 'Отключить',
    refresh: 'Обновить',
    accountInfo: 'Информация об аккаунте',
    trafficUsage: 'Использование трафика',
    trafficLimit: 'Лимит трафика',
    timeRemaining: 'Оставшееся время',
    remaining: 'осталось',
    expiresAt: 'Истекает',
    createdAt: 'Создан',
    connectionHistory: 'История подключений',
    enabledProtocols: 'Доступные протоколы',
    active: 'Активен',
    onHold: 'Приостановлен',
    home: 'Главная',
    account: 'Аккаунт',
    protocols: 'Протоколы',
    autoReconnect: 'Автоподключение',
    autoReconnectDesc: 'Автоматическое переподключение при обрыве',
    killSwitch: 'Kill Switch',
    killSwitchDesc: 'Блокировать интернет при отключении VPN',
    dnsLeakProtection: 'Защита от утечки DNS',
    dnsLeakProtectionDesc: 'Предотвращение DNS-запросов вне VPN-туннеля',
    splitTunneling: 'Раздельное туннелирование',
    splitTunnelingDesc: 'Направлять только выбранные приложения через VPN',
    security: 'Безопасность',
    general: 'Общие',
    server: 'Сервер',
    confirmLogout: 'Вы уверены, что хотите выйти?',
    autoPilot: 'Автопилот',
    autoPilotDesc: 'Автоматическое переключение на лучшее соединение',
    findBestConnection: '🔍 Найти лучшее соединение',
  },
  zh: {
    settings: '设置',
    appearance: '外观',
    theme: '主题',
    lightMode: '浅色模式',
    darkMode: '深色模式',
    language: '语言',
    autoUpdate: '自动更新',
    autoUpdateDesc: '自动更新应用程序',
    english: '英语',
    persian: '波斯语',
    russian: '俄语',
    chinese: '中文',
    candyConnect: 'CandyConnect',
    cores: '内核',
    v2rayCore: 'V2ray 内核',
    wireGuard: 'WireGuard',
    singBox: 'Sing-Box',
    xray: 'Xray',
    amnezia: 'Amnezia',
    nativeWireGuard: '原生 WireGuard',
    profiles: '配置文件',
    proxy: '代理',
    about: '关于',
    version: '版本',
    github: 'GitHub',
    description: '支持多核心的现代 VPN 客户端',
    logs: '日志',
    addProfile: '添加配置',
    editProfile: '编辑配置',
    deleteProfile: '删除配置',
    deleteProfiles: '删除配置',
    selectProfile: '选择配置',
    profileName: '配置名称',
    profileUrl: '配置链接',
    fromClipboard: '从剪贴板',
    fromQRCode: '从二维码',
    manually: '手动输入',
    cancel: '取消',
    save: '保存',
    delete: '删除',
    edit: '编辑',
    select: '选择',
    selected: '已选择',
    noProfiles: '没有可用的配置',
    confirmDelete: '确定要删除此配置吗？',
    confirmDeleteMultiple: '确定要删除选中的配置吗？',
    connectionMode: '连接模式',
    selectConnectionMode: '选择您首选的连接模式',
    proxyType: '代理类型',
    selectProxyType: '选择代理协议',
    connectionSettings: '连接设置',
    configureProxyConnection: '配置代理服务器连接',
    ipAddress: 'IP 地址',
    port: '端口',
    authentication: '身份验证',
    enableAuthIfRequired: '如果您的代理需要身份验证请启用',
    username: '用户名',
    password: '密码',
    enterUsername: '输入用户名',
    enterPassword: '输入密码',
    tunModeActive: 'TUN 模式已激活',
    tunModeInfo: 'TUN 模式创建虚拟网络接口用于系统级流量路由。',
    tunModeDesc: '系统级路由',
    proxyModeDesc: '应用级代理',
    socksProxyDesc: 'SOCKS5 协议',
    httpProxyDesc: 'HTTP/HTTPS 协议',
    currentSettings: '当前设置',
    mode: '模式',
    type: '类型',
    address: '地址',
    enabled: '已启用',
    disabled: '已禁用',
    vpnClient: 'VPN 客户端',
    serverAddress: '服务器地址',
    login: '登录',
    logout: '退出',
    rememberMe: '记住我',
    loginFailed: '登录失败',
    connectionError: '无法连接到服务器',
    connecting: '连接中',
    fillAllFields: '请填写所有字段',
    selectProtocol: '选择协议',
    protocolStatus: '状态',
    activeConnections: '活跃连接',
    connected: '已连接',
    disconnected: '已断开',
    offline: '离线',
    connect: '连接',
    disconnect: '断开',
    refresh: '刷新',
    accountInfo: '账户信息',
    trafficUsage: '流量使用',
    trafficLimit: '流量限制',
    timeRemaining: '剩余时间',
    remaining: '剩余',
    expiresAt: '到期时间',
    createdAt: '创建时间',
    connectionHistory: '连接历史',
    enabledProtocols: '可用协议',
    active: '活跃',
    onHold: '暂停',
    home: '首页',
    account: '账户',
    protocols: '协议',
    autoReconnect: '自动重连',
    autoReconnectDesc: '断线时自动重新连接',
    killSwitch: '终止开关',
    killSwitchDesc: 'VPN断开时阻止网络',
    dnsLeakProtection: 'DNS泄漏保护',
    dnsLeakProtectionDesc: '防止VPN隧道外的DNS查询',
    splitTunneling: '分流隧道',
    splitTunnelingDesc: '仅将选定应用通过VPN路由',
    security: '安全',
    general: '通用',
    server: '服务器',
    confirmLogout: '确定要退出吗？',
    autoPilot: '自动驾驶',
    autoPilotDesc: '自动切换到最佳连接',
    findBestConnection: '🔍 寻找最佳连接',
  },
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('candyconnect-language') as Language;
    if (savedLanguage && ['en', 'fa', 'ru', 'zh'].includes(savedLanguage)) {
      return savedLanguage;
    }
    return 'en';
  });

  const isRTL = language === 'fa';

  useEffect(() => {
    localStorage.setItem('candyconnect-language', language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
